#!/usr/bin/env zsh
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

function can {
  type -p $1 2>&1 >/dev/null
}

if [[ "$OSTYPE" == darwin* ]]; then
  DARWIN=1
else
  LINUX=1
fi

# #
# # Browser
# #

# if [[ "$OSTYPE" == darwin* ]]; then
#   export BROWSER='open'
# fi

#
# Editors
#

if [ $DARWIN ]; then
  export EDITOR='subl --new-window'
  export GIT_EDITOR="$EDITOR --wait"
  export VISUAL=$EDITOR
else
  export EDITOR='vim'
  export VISUAL='vim'
fi

export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.

#FIXME: needed?
if [[ -d ~/.rbenv ]]; then
  path=(
    ~/.rbenv
    $path
  )
fi

if [[ -d /usr/local ]]; then
  path=(
    /usr/local/{bin,sbin}
    $path
  )
fi

# #FIXME: needed?
# if can brew; then
#   path=(
#     $(/usr/local/bin/brew --prefix ruby)/bin
#     $path
#   )
# fi

if [[ -d ~/bin ]]; then
  path=(
    ~/bin
    $path
  )
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
# export LESS='-F -g -i -M -R -S -w -X -z-4'
export LESS='--clear-screen --quit-at-eof --ignore-case --LONG-PROMPT --squeeze-blank-lines --QUIET --RAW-CONTROL-CHARS'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# #FIXME: needed?
# #
# # setup rbenv
# #

# if can rbenv; then
#   eval "$(rbenv init -)"
# fi